-- Causeries mathématiques — 1er cycle (1re-2e année)
DO $$
DECLARE
  math_id integer;
BEGIN
  SELECT id INTO math_id FROM subjects WHERE name_fr ILIKE '%math%' ORDER BY id LIMIT 1;

  IF EXISTS (
    SELECT 1 FROM activity_templates
    WHERE category = 'Causerie — Nombres' AND grade_level_tag = '1re année'
    LIMIT 1
  ) THEN RETURN; END IF;

  INSERT INTO activity_templates
    (title, description, subject_id, type_tag, duration_min, grade_level_tag, category,
     open_question, expected_strategies, observation_criteria, pda_link)
  VALUES

  -- ── 1. Nombres ─────────────────────────────────────────────────────────────
  ('Reconnaître 1 à 6',
   'Combien de points vois-tu? Comment le sais-tu sans compter?',
   math_id, 'Cartes à points', 15, '1re année', 'Causerie — Nombres',
   'Combien de points vois-tu? Comment le sais-tu sans compter?',
   'Reconnaître des configurations connues (dés, doigts)',
   'Cartes à points (1-5)', 'Arithmétique – Nombres naturels'),

  ('Reconnaître 7 à 12',
   'Je te montre une image 3 secondes. Combien de points as-tu vus?',
   math_id, 'Subitisation', 15, '1re-2e année', 'Causerie — Nombres',
   'Je te montre une image 3 secondes. Combien de points as-tu vus?',
   'Regrouper en sous-ensembles connus (3+4=7)',
   'Cartes à points (6-10)', 'Arithmétique – Nombres naturels'),

  ('Configurations du dé',
   'Montre-moi 6 avec tes doigts. Montre-le d''une autre façon.',
   math_id, 'Cartes à points', 15, '1re année', 'Causerie — Nombres',
   'Montre-moi 6 avec tes doigts. Montre-le d''une autre façon.',
   'Reconnaître la disposition du dé',
   'Dés, doigts', 'Arithmétique – Nombres naturels'),

  ('Points désorganisés',
   'Combien y a-t-il de points? Est-ce plus facile quand ils sont en ligne?',
   math_id, 'Subitisation', 15, '2e année', 'Causerie — Nombres',
   'Combien y a-t-il de points? Est-ce plus facile quand ils sont en ligne?',
   'Compter par groupes, organiser mentalement',
   'Cartes à points variées', 'Arithmétique – Nombres naturels'),

  ('Compter par bonds de 2',
   'Comptez ensemble par bonds de 2 à partir de 0. Que remarquez-vous?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Nombres',
   'Comptez ensemble par bonds de 2 à partir de 0. Que remarquez-vous?',
   'Suite régulière, nombres pairs',
   'Droite numérique', 'Arithmétique – Dénombrement'),

  ('Compter par bonds de 5',
   'Comptez par bonds de 5 à partir de 5 jusqu''à 50. Que remarquez-vous?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Nombres',
   'Comptez par bonds de 5 à partir de 5 jusqu''à 50. Que remarquez-vous?',
   'Reconnaître la récurrence de 5-0 dans les unités',
   'Droite numérique', 'Arithmétique – Dénombrement'),

  ('Compter par bonds de 10',
   'Comptez par bonds de 10 à partir de 3. Que reste pareil? Que change?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Nombres',
   'Comptez par bonds de 10 à partir de 3. Que reste pareil? Que change?',
   'Le chiffre des unités reste le même',
   'Tableau de 100', 'Arithmétique – Dénombrement'),

  ('Combien sont cachés? (Splat)',
   'J''avais 8 jetons. Splat en cache quelques-uns. Il en reste 5. Combien sont cachés?',
   math_id, 'Splat', 15, '1re année', 'Causerie — Nombres',
   'J''avais 8 jetons. Splat en cache quelques-uns. Il en reste 5. Combien sont cachés?',
   'Compter à partir de 5, soustraire de 8',
   'Jetons, image Splat', 'Arithmétique – Sens des opérations'),

  ('Mon nombre secret (dizaines)',
   'J''ai un nombre entre 30 et 50. Il a 4 dizaines. Il est pair. Quel est-il?',
   math_id, 'Devine combien', 15, '2e année', 'Causerie — Nombres',
   'J''ai un nombre entre 30 et 50. Il a 4 dizaines. Il est pair. Quel est-il?',
   'Éliminer selon les indices, identifier la dizaine',
   'Tableau de 100', 'Arithmétique – Valeur de position'),

  ('Unités et dizaines',
   'Mon nombre a 3 dizaines et 5 unités. Quel est mon nombre?',
   math_id, 'Devine combien', 15, '1re-2e année', 'Causerie — Nombres',
   'Mon nombre a 3 dizaines et 5 unités. Quel est mon nombre?',
   'Combiner dizaines et unités',
   'Matériel base 10', 'Arithmétique – Valeur de position'),

  ('Décomposer avec base 10',
   'Représente 47 avec du matériel base 10. Combien de dizaines? D''unités?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Nombres',
   'Représente 47 avec du matériel base 10. Combien de dizaines? D''unités?',
   'Grouper en paquets de 10',
   'Blocs base 10', 'Arithmétique – Valeur de position'),

  ('Centaines, dizaines, unités',
   'Mon nombre a 2 centaines, 0 dizaine et 3 unités. Quel est-il?',
   math_id, 'Devine combien', 15, '2e année', 'Causerie — Nombres',
   'Mon nombre a 2 centaines, 0 dizaine et 3 unités. Quel est-il?',
   'Comprendre la position de chaque chiffre',
   'Matériel base 10', 'Arithmétique – Valeur de position | jusqu''à 300'),

  ('Quel nombre n''appartient pas?',
   'Voici 4 nombres : 12, 15, 20, 25. Lequel n''appartient pas au groupe? Pourquoi?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Nombres',
   'Voici 4 nombres : 12, 15, 20, 25. Lequel n''appartient pas au groupe? Pourquoi?',
   'Identifier une caractéristique commune, justifier',
   'Cartes nombres', 'Arithmétique – Propriétés des nombres'),

  ('Comparaison de représentations',
   'Voici : 3 dizaines, 30, vingt-dix, XXX. Lequel est différent? Pourquoi?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Nombres',
   'Voici : 3 dizaines, 30, vingt-dix, XXX. Lequel est différent? Pourquoi?',
   'Comparer différentes écritures d''un nombre',
   'Cartes', 'Arithmétique – Représentations'),

  ('Plus grand, plus petit, égal',
   'Compare 34 et 43. Lequel est le plus grand? Comment le sais-tu?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Nombres',
   'Compare 34 et 43. Lequel est le plus grand? Comment le sais-tu?',
   'Comparer les dizaines d''abord, puis les unités',
   'Cartes nombres', 'Arithmétique – Ordre'),

  ('Ranger du plus petit au plus grand',
   'Range ces nombres en ordre croissant : 58, 17, 82, 41. Explique ta stratégie.',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Nombres',
   'Range ces nombres en ordre croissant : 58, 17, 82, 41. Explique ta stratégie.',
   'Utiliser la valeur de position pour ordonner',
   'Cartes nombres', 'Arithmétique – Ordre'),

  ('Ordre et comparaison',
   '14, 41, 22, 33 – Lequel est différent? Trouve au moins 2 raisons.',
   math_id, 'WODB', 15, '2e année', 'Causerie — Nombres',
   '14, 41, 22, 33 – Lequel est différent? Trouve au moins 2 raisons.',
   'Analyser dizaines vs unités, pair/impair',
   'Tableau blanc', 'Arithmétique – Ordre'),

  ('Trois façons de montrer 24',
   'Trouve 3 façons différentes de représenter le nombre 24.',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Nombres',
   'Trouve 3 façons différentes de représenter le nombre 24.',
   'Dessins, mots, base 10, addition, droite numérique',
   'Matériel varié', 'Arithmétique – Représentations'),

  ('Cadre de 10 – représenter',
   'Montre le nombre 8 dans un cadre de 10. Combien de cases vides?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Nombres',
   'Montre le nombre 8 dans un cadre de 10. Combien de cases vides?',
   'Complémentaire à 10',
   'Cadres de 10, jetons', 'Arithmétique – Représentations'),

  ('Combien dans le pot?',
   'Combien de crayons y a-t-il dans ce pot? Donne une estimation.',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Nombres',
   'Combien de crayons y a-t-il dans ce pot? Donne une estimation.',
   'Utiliser un référent connu pour estimer',
   'Pot de crayons', 'Arithmétique – Estimation'),

  ('La fraction ½',
   'Si je coupe cette pizza en 2 parts égales et que j''en mange 1, quelle fraction ai-je mangée?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Nombres',
   'Si je coupe cette pizza en 2 parts égales et que j''en mange 1, quelle fraction ai-je mangée?',
   'Partager en parts égales, nommer la fraction',
   'Image pizza', 'Arithmétique – Fractions'),

  ('La fraction ¼',
   'Si je coupe cette pizza en 4 parts égales et que j''en mange 1, quelle fraction ai-je mangée?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Nombres',
   'Si je coupe cette pizza en 4 parts égales et que j''en mange 1, quelle fraction ai-je mangée?',
   'Identifier le tout et la partie',
   'Image pizza/tablette chocolat', 'Arithmétique – Fractions'),

  ('Comparer des fractions',
   '½ d''une pomme, ¼ d''une pomme, ⅓ d''une pomme, 1 pomme entière – Lequel est différent?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Nombres',
   '½ d''une pomme, ¼ d''une pomme, ⅓ d''une pomme, 1 pomme entière – Lequel est différent?',
   'Comparer les parties au tout',
   'Images de fractions', 'Arithmétique – Fractions'),

  ('Suite numérique +2',
   'Quelle est la suite : 2, 4, 6, 8, __? Quel est le prochain nombre? La règle?',
   math_id, 'Régularités', 15, '1re année', 'Causerie — Nombres',
   'Quelle est la suite : 2, 4, 6, 8, __? Quel est le prochain nombre? La règle?',
   'Identifier la règle récurrente',
   'Cartes nombres', 'Arithmétique – Régularités'),

  ('Suite numérique +5',
   'Continue la suite : 5, 10, 15, 20, __. Comment as-tu trouvé?',
   math_id, 'Régularités', 15, '1re-2e année', 'Causerie — Nombres',
   'Continue la suite : 5, 10, 15, 20, __. Comment as-tu trouvé?',
   'Appliquer la règle de la suite',
   'Droite numérique', 'Arithmétique – Régularités'),

  ('Trouver l''erreur dans la suite',
   'Voici une suite : 3, 6, 9, 11, 15. Y a-t-il une erreur? Où? Corrige-la.',
   math_id, 'Régularités', 15, '2e année', 'Causerie — Nombres',
   'Voici une suite : 3, 6, 9, 11, 15. Y a-t-il une erreur? Où? Corrige-la.',
   'Vérifier chaque bond, trouver l''irrégularité',
   'Tableau blanc', 'Arithmétique – Régularités'),

  ('Lire un nombre',
   'Lis ce nombre : 156. Comment dit-on ce nombre en mots?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Nombres',
   'Lis ce nombre : 156. Comment dit-on ce nombre en mots?',
   'Correspondance chiffre-mot, valeur de position',
   'Cartes nombres', 'Arithmétique – Lecture et écriture'),

  ('Écrire un nombre entendu',
   'J''ai dit « quatre-vingt-treize ». Écris-le en chiffres sur ton tableau.',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Nombres',
   'J''ai dit « quatre-vingt-treize ». Écris-le en chiffres sur ton tableau.',
   'Conversion oral → écrit',
   'Tableau blanc individuel', 'Arithmétique – Lecture et écriture'),

  -- ── 2. Opérations ──────────────────────────────────────────────────────────
  ('Doubles (1+1 à 5+5)',
   'Combien font 4 + 4? Comment le sais-tu? Connais-tu d''autres doubles?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Opérations',
   'Combien font 4 + 4? Comment le sais-tu? Connais-tu d''autres doubles?',
   'Mémorisation des doubles, lien avec le dénombrement',
   'Cartes éclairs doubles', 'Arithmétique – Addition'),

  ('Doubles +1',
   'Comment peux-tu calculer 6 + 7 dans ta tête? Partage ta stratégie.',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Opérations',
   'Comment peux-tu calculer 6 + 7 dans ta tête? Partage ta stratégie.',
   '6+6=12, donc 6+7=13; ou 7+7=14, donc 6+7=13',
   'Tableau blanc', 'Arithmétique – Addition'),

  ('Faire 10',
   'Comment peux-tu calculer 8 + 5 dans ta tête? Utilise la stratégie « faire 10 ».',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Comment peux-tu calculer 8 + 5 dans ta tête? Utilise la stratégie « faire 10 ».',
   '8+2=10, il reste 3, donc 8+5=13',
   'Cadre de 10, jetons', 'Arithmétique – Addition'),

  ('Addition – combien cachés?',
   'Il y avait 10 coccinelles. Splat! Il en reste 4. Combien sont cachées?',
   math_id, 'Splat', 15, '1re année', 'Causerie — Opérations',
   'Il y avait 10 coccinelles. Splat! Il en reste 4. Combien sont cachées?',
   'Compter à partir de 4, soustraire de 10',
   'Image Splat, jetons', 'Arithmétique – Addition'),

  ('Compter à partir de',
   'Calcule 3 + 9. Par quel nombre commences-tu à compter? Pourquoi?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Opérations',
   'Calcule 3 + 9. Par quel nombre commences-tu à compter? Pourquoi?',
   'Commencer par 9 et ajouter 3',
   'Droite numérique', 'Arithmétique – Addition'),

  ('Somme proche de 10 ou 20?',
   'Est-ce que 6 + 8 est plus près de 10 ou de 20? Comment le sais-tu?',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Opérations',
   'Est-ce que 6 + 8 est plus près de 10 ou de 20? Comment le sais-tu?',
   'Arrondir mentalement, encadrer le résultat',
   'Droite numérique', 'Arithmétique – Estimation'),

  ('Soustraire – compter à rebours',
   'Calcule 12 – 3 dans ta tête. Quelle stratégie as-tu utilisée?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Opérations',
   'Calcule 12 – 3 dans ta tête. Quelle stratégie as-tu utilisée?',
   'Partir de 12 et reculer de 3',
   'Droite numérique', 'Arithmétique – Soustraction'),

  ('Soustraction avec Splat',
   'Il y avait 15 bonbons. Splat! Il en reste 9. Combien sont cachés?',
   math_id, 'Splat', 15, '1re-2e année', 'Causerie — Opérations',
   'Il y avait 15 bonbons. Splat! Il en reste 9. Combien sont cachés?',
   '15 – 9 = 6, ou compter de 9 à 15',
   'Image Splat, jetons', 'Arithmétique – Soustraction'),

  ('Lien addition-soustraction',
   'Si 7 + 5 = 12, que vaut 12 – 5? Comment le sais-tu?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Si 7 + 5 = 12, que vaut 12 – 5? Comment le sais-tu?',
   'Utiliser le fait d''addition connu',
   'Cartes de faits numériques', 'Arithmétique – Soustraction'),

  ('Soustraire en décomposant',
   'Calcule 14 – 6 dans ta tête. Y a-t-il plus d''une façon?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Calcule 14 – 6 dans ta tête. Y a-t-il plus d''une façon?',
   '14–4=10, 10–2=8; ou 14–6: compter de 6 à 14',
   'Tableau blanc', 'Arithmétique – Soustraction'),

  ('Double Splat',
   'Il y avait 12 étoiles. Splat! Splat! Un Splat cache 4, l''autre cache combien? Il en reste 5.',
   math_id, 'Splat', 15, '2e année', 'Causerie — Opérations',
   'Il y avait 12 étoiles. Splat! Splat! Un Splat cache 4, l''autre cache combien? Il en reste 5.',
   '12 – 4 – 3 = 5, ou additionner les parties connues',
   'Image Double Splat', 'Arithmétique – Soustraction'),

  ('Calcul mental – ajouter 10',
   'Calcule 27 + 10 dans ta tête. Que remarques-tu?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Opérations',
   'Calcule 27 + 10 dans ta tête. Que remarques-tu?',
   'Seul le chiffre des dizaines change',
   'Tableau de 100', 'Arithmétique – Calcul mental'),

  ('Calcul mental – ajouter 9',
   'Calcule 15 + 9. Quelle astuce peux-tu utiliser?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Calcule 15 + 9. Quelle astuce peux-tu utiliser?',
   'Stratégie +10 –1 : 15+10=25, 25–1=24',
   'Tableau blanc', 'Arithmétique – Calcul mental'),

  ('Calcul mental – doubles de grands nombres',
   'Combien font 25 + 25? Comment as-tu fait?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Combien font 25 + 25? Comment as-tu fait?',
   'Doubler les dizaines, doubler les unités, additionner',
   'Tableau blanc', 'Arithmétique – Calcul mental'),

  ('Décomposer pour additionner',
   'Calcule 18 + 14. Décompose les nombres pour t''aider.',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Calcule 18 + 14. Décompose les nombres pour t''aider.',
   '18+14 = 18+2+12 = 20+12 = 32',
   'Matériel base 10', 'Arithmétique – Calcul mental'),

  ('Stratégies multiples',
   'Trouve au moins 2 façons de calculer 7 + 8.',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Opérations',
   'Trouve au moins 2 façons de calculer 7 + 8.',
   'Doubles +1, faire 10, compter à partir de',
   'Tableau blanc', 'Arithmétique – Calcul mental'),

  ('Estimation avant de calculer',
   'Avant de calculer 23 + 19, estime la réponse. Sera-t-elle plus proche de 30, 40 ou 50?',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Opérations',
   'Avant de calculer 23 + 19, estime la réponse. Sera-t-elle plus proche de 30, 40 ou 50?',
   'Arrondir : 20+20=40, donc environ 40',
   'Tableau blanc', 'Arithmétique – Estimation'),

  ('Estimer une soustraction',
   'Sans calculer : 50 – 28, est-ce plus proche de 10, 20 ou 30?',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Opérations',
   'Sans calculer : 50 – 28, est-ce plus proche de 10, 20 ou 30?',
   '50–30=20, donc environ 20',
   'Droite numérique', 'Arithmétique – Estimation'),

  ('Quelle addition est différente?',
   '3+5, 4+4, 2+7, 6+2 – Quelle addition n''appartient pas? Pourquoi?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Opérations',
   '3+5, 4+4, 2+7, 6+2 – Quelle addition n''appartient pas? Pourquoi?',
   'Identifier que 4+4 est un double, 6+2=8 vs 3+5=8',
   'Cartes', 'Arithmétique – Propriétés des opérations'),

  ('Problème – ajout',
   'Léa a 8 billes. Son ami lui en donne 6. Combien en a-t-elle maintenant?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Opérations',
   'Léa a 8 billes. Son ami lui en donne 6. Combien en a-t-elle maintenant?',
   'Compter à partir de 8, faire 10 puis ajouter',
   'Jetons, dessin', 'Arithmétique – Situations (ajout)'),

  ('Problème – retrait',
   'Marc avait 15 autocollants. Il en donne 7 à son ami. Combien lui en reste-t-il?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Opérations',
   'Marc avait 15 autocollants. Il en donne 7 à son ami. Combien lui en reste-t-il?',
   'Compter à rebours, décomposer 7',
   'Jetons, dessin', 'Arithmétique – Situations (retrait)'),

  ('Problème – comparaison',
   'Zoé a 12 crayons et Théo en a 8. Combien Zoé en a-t-elle de plus que Théo?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Zoé a 12 crayons et Théo en a 8. Combien Zoé en a-t-elle de plus que Théo?',
   'Trouver l''écart, compter de 8 à 12',
   'Dessin, droite numérique', 'Arithmétique – Situations (comparaison)'),

  ('Problème – réunion',
   'Il y a 10 stylos rouges et 7 stylos bleus sur le bureau. Combien y en a-t-il en tout?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Opérations',
   'Il y a 10 stylos rouges et 7 stylos bleus sur le bureau. Combien y en a-t-il en tout?',
   '10+7=17, ou faire 10 puis ajouter',
   'Jetons', 'Arithmétique – Situations (réunion)'),

  ('Commutativité',
   '3 + 5 et 5 + 3 donnent-ils la même réponse? Est-ce toujours vrai? Essaie avec d''autres nombres.',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Opérations',
   '3 + 5 et 5 + 3 donnent-ils la même réponse? Est-ce toujours vrai? Essaie avec d''autres nombres.',
   'Tester plusieurs exemples pour généraliser',
   'Jetons, cubes', 'Arithmétique – Propriétés des opérations'),

  ('Quel groupe de bonbons?',
   'Préfères-tu avoir 5 + 5 bonbons ou 3 + 8 bonbons? Pourquoi?',
   math_id, 'Que choisirais-tu?', 15, '1re-2e année', 'Causerie — Opérations',
   'Préfères-tu avoir 5 + 5 bonbons ou 3 + 8 bonbons? Pourquoi?',
   'Calculer chaque somme, comparer',
   'Images bonbons', 'Arithmétique – Équivalence'),

  ('Résultat raisonnable?',
   'Un ami dit que 9 + 8 = 21. Est-ce raisonnable? Comment le sais-tu?',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Opérations',
   'Un ami dit que 9 + 8 = 21. Est-ce raisonnable? Comment le sais-tu?',
   '9+9=18, donc 9+8 doit être moins que 18',
   'Tableau blanc', 'Arithmétique – Estimation'),

  ('Chaîne d''opérations',
   'Calcule : 5 + 3 – 2 + 4. Explique étape par étape.',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Opérations',
   'Calcule : 5 + 3 – 2 + 4. Explique étape par étape.',
   'Calculer de gauche à droite, garder le total en tête',
   'Tableau blanc', 'Arithmétique – Calcul mental'),

  -- ── 3. Géométrie ───────────────────────────────────────────────────────────
  ('Figures planes – laquelle est différente?',
   'Voici 4 figures : carré, rectangle, triangle, cercle. Laquelle n''appartient pas? Pourquoi?',
   math_id, 'WODB', 15, '1re année', 'Causerie — Géométrie',
   'Voici 4 figures : carré, rectangle, triangle, cercle. Laquelle n''appartient pas? Pourquoi?',
   'Identifier nombre de côtés, lignes droites/courbes',
   'Figures découpées', 'Géométrie – Figures planes'),

  ('Combien de côtés?',
   'Combien de côtés a un triangle? Un carré? Un rectangle? Que remarques-tu?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Géométrie',
   'Combien de côtés a un triangle? Un carré? Un rectangle? Que remarques-tu?',
   'Compter les côtés, comparer',
   'Figures géométriques', 'Géométrie – Figures planes'),

  ('Quadrilatères',
   'Carré, rectangle, losange, triangle – Lequel est différent? Trouve plusieurs raisons.',
   math_id, 'WODB', 15, '2e année', 'Causerie — Géométrie',
   'Carré, rectangle, losange, triangle – Lequel est différent? Trouve plusieurs raisons.',
   'Nombre de côtés, angles, côtés égaux',
   'Figures découpées', 'Géométrie – Figures planes'),

  ('Trouver des figures dans la classe',
   'Regarde autour de toi. Peux-tu trouver 3 objets qui ont la forme d''un rectangle?',
   math_id, 'Estimation', 15, '1re année', 'Causerie — Géométrie',
   'Regarde autour de toi. Peux-tu trouver 3 objets qui ont la forme d''un rectangle?',
   'Observer, associer forme géométrique et objet réel',
   'Environnement de classe', 'Géométrie – Figures planes'),

  ('Figures ouvertes et fermées',
   'Est-ce que cette figure est ouverte ou fermée? Comment le sais-tu?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Géométrie',
   'Est-ce que cette figure est ouverte ou fermée? Comment le sais-tu?',
   'Vérifier si la ligne revient à son point de départ',
   'Dessins au tableau', 'Géométrie – Figures planes'),

  ('Solides – lequel est différent?',
   'Cube, sphère, cylindre, cône – Lequel est différent? Pourquoi?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Géométrie',
   'Cube, sphère, cylindre, cône – Lequel est différent? Pourquoi?',
   'Faces plates/courbes, roule/glisse',
   'Solides géométriques', 'Géométrie – Solides'),

  ('Combien de faces?',
   'Combien de faces a ce cube? Montre-moi avec tes doigts avant de vérifier.',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Géométrie',
   'Combien de faces a ce cube? Montre-moi avec tes doigts avant de vérifier.',
   'Estimer puis compter systématiquement',
   'Cube en bois/plastique', 'Géométrie – Solides'),

  ('Ça roule ou ça glisse?',
   'Ce solide roule-t-il ou glisse-t-il? Comment le sais-tu? Pourquoi?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Géométrie',
   'Ce solide roule-t-il ou glisse-t-il? Comment le sais-tu? Pourquoi?',
   'Lien entre faces courbes (roule) et faces plates (glisse)',
   'Solides variés', 'Géométrie – Solides'),

  ('Deviner le solide',
   'Mon solide a 6 faces carrées identiques. Il ne roule pas. Quel est-il?',
   math_id, 'Devine combien', 15, '2e année', 'Causerie — Géométrie',
   'Mon solide a 6 faces carrées identiques. Il ne roule pas. Quel est-il?',
   'Éliminer selon les indices (faces, forme)',
   'Collection de solides', 'Géométrie – Solides'),

  ('Ligne droite ou courbe?',
   'Trace une ligne droite et une ligne courbe. Quelle est la différence?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Géométrie',
   'Trace une ligne droite et une ligne courbe. Quelle est la différence?',
   'Observer la direction, utiliser une règle',
   'Tableau blanc, règle', 'Géométrie – Lignes'),

  ('Types de lignes',
   'Ligne droite, ligne courbe, ligne brisée, ligne fermée – Laquelle est différente?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Géométrie',
   'Ligne droite, ligne courbe, ligne brisée, ligne fermée – Laquelle est différente?',
   'Identifier les caractéristiques de chaque type',
   'Dessins au tableau', 'Géométrie – Lignes'),

  ('Lignes dans les figures',
   'Le carré est fait de quelles sortes de lignes? Et le cercle?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Géométrie',
   'Le carré est fait de quelles sortes de lignes? Et le cercle?',
   'Droites pour le carré, courbe pour le cercle',
   'Figures géométriques', 'Géométrie – Lignes'),

  ('Continue la frise',
   'Quelle sera la prochaine figure dans cette frise : ○□△○□△○□…?',
   math_id, 'Régularités', 15, '1re année', 'Causerie — Géométrie',
   'Quelle sera la prochaine figure dans cette frise : ○□△○□△○□…?',
   'Identifier le motif qui se répète (période)',
   'Formes découpées', 'Géométrie – Frises et régularités'),

  ('Crée ta propre frise',
   'Invente une frise avec 2 formes. Montre-la à ton voisin. Peut-il la continuer?',
   math_id, 'Régularités', 15, '1re-2e année', 'Causerie — Géométrie',
   'Invente une frise avec 2 formes. Montre-la à ton voisin. Peut-il la continuer?',
   'Choisir un motif et le répéter de façon régulière',
   'Formes, crayons couleur', 'Géométrie – Frises et régularités'),

  ('Frise avec couleurs et formes',
   'Frise : □rouge, ○bleu, △vert, □rouge, ○bleu, △vert… Quel sera le 10e élément?',
   math_id, 'Régularités', 15, '2e année', 'Causerie — Géométrie',
   'Frise : □rouge, ○bleu, △vert, □rouge, ○bleu, △vert… Quel sera le 10e élément?',
   'Compter la période (3), diviser, trouver la position',
   'Formes colorées', 'Géométrie – Frises et régularités'),

  ('Se repérer dans la classe',
   'Place-toi devant la porte. Qu''est-ce qui est à ta gauche? À ta droite? Derrière toi?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Géométrie',
   'Place-toi devant la porte. Qu''est-ce qui est à ta gauche? À ta droite? Derrière toi?',
   'Utiliser les termes : devant, derrière, à gauche, à droite',
   'Environnement de classe', 'Géométrie – Repérage spatial'),

  ('Décrire un trajet',
   'Explique comment aller de ton pupitre à la bibliothèque : avance, tourne, à droite, à gauche.',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Géométrie',
   'Explique comment aller de ton pupitre à la bibliothèque. Utilise : avance, tourne, à droite, à gauche.',
   'Utiliser le vocabulaire spatial de façon précise',
   'Plan de la classe', 'Géométrie – Repérage spatial'),

  ('Repérage sur quadrillage',
   'Sur ce quadrillage, où est placée l''étoile? Utilise les mots ligne et colonne.',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Géométrie',
   'Sur ce quadrillage, où est placée l''étoile? Utilise les mots ligne et colonne.',
   'Nommer la position avec ligne et colonne',
   'Quadrillage affiché', 'Géométrie – Repérage spatial'),

  ('Symétrie – pliage',
   'Si je plie cette image en deux, les deux côtés sont-ils pareils? Comment le sais-tu?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Géométrie',
   'Si je plie cette image en deux, les deux côtés sont-ils pareils? Comment le sais-tu?',
   'Plier pour vérifier, observer la correspondance',
   'Papier, miroir', 'Géométrie – Symétrie'),

  ('Figures symétriques',
   'Carré, rectangle, triangle scalène, cercle – Laquelle n''a PAS de symétrie?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Géométrie',
   'Voici 4 figures : carré, rectangle, triangle scalène, cercle. Laquelle n''a PAS de symétrie?',
   'Identifier les axes de symétrie possibles',
   'Figures, miroir', 'Géométrie – Symétrie'),

  -- ── 4. Mesure ──────────────────────────────────────────────────────────────
  ('Estimer la longueur en trombones',
   'Combien de trombones mesure ton crayon? Estime, puis vérifie.',
   math_id, 'Estimation', 15, '1re année', 'Causerie — Mesure',
   'Combien de trombones mesure ton crayon? Estime, puis vérifie.',
   'Estimer en utilisant un référent connu, vérifier',
   'Trombones, crayons', 'Mesure – Longueur (unités non conventionnelles)'),

  ('Plus long ou plus court?',
   'Est-ce que ton bras est plus long ou plus court que ta jambe? Comment peux-tu vérifier?',
   math_id, 'Estimation', 15, '1re année', 'Causerie — Mesure',
   'Est-ce que ton bras est plus long ou plus court que ta jambe? Comment peux-tu vérifier?',
   'Comparer directement ou avec un outil',
   'Ficelle, règle', 'Mesure – Longueur'),

  ('Mesurer en centimètres',
   'Mesure la longueur de ton livre avec une règle. Combien de centimètres?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Mesure',
   'Mesure la longueur de ton livre avec une règle. Combien de centimètres?',
   'Aligner le 0 de la règle, lire la graduation',
   'Règle graduée en cm', 'Mesure – Longueur (unités conventionnelles)'),

  ('Unités de longueur',
   'Trombone, pas de géant, centimètre, main – Lequel est différent pour mesurer?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Mesure',
   'Trombone, pas de géant, centimètre, main – Lequel est différent pour mesurer?',
   'Distinguer unité standardisée vs variable',
   'Objets de mesure', 'Mesure – Longueur'),

  ('Quel outil pour mesurer?',
   'Pour mesurer la longueur du corridor, utiliserais-tu un trombone ou un mètre? Pourquoi?',
   math_id, 'Que choisirais-tu?', 15, '2e année', 'Causerie — Mesure',
   'Pour mesurer la longueur du corridor, utiliserais-tu un trombone ou un mètre? Pourquoi?',
   'Efficacité, praticité de l''unité choisie',
   'Mètre, trombones', 'Mesure – Longueur'),

  ('Les jours de la semaine',
   'Quel jour sommes-nous? Quel jour étions-nous hier? Quel jour serons-nous demain?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Mesure',
   'Quel jour sommes-nous? Quel jour étions-nous hier? Quel jour serons-nous demain?',
   'Utiliser l''ordre des jours, vocabulaire temporel',
   'Calendrier de classe', 'Mesure – Temps'),

  ('Les mois de l''année',
   'Quel mois sommes-nous? Quel mois vient après? Combien de mois y a-t-il dans une année?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Mesure',
   'Quel mois sommes-nous? Quel mois vient après? Combien de mois y a-t-il dans une année?',
   'Réciter la séquence des mois',
   'Calendrier', 'Mesure – Temps'),

  ('Lire l''heure – heure pile',
   'Il est 3 heures. Où sont les aiguilles de l''horloge? La grande? La petite?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Mesure',
   'Il est 3 heures. Où sont les aiguilles de l''horloge? La grande? La petite?',
   'Identifier la petite aiguille (heure) et la grande (minutes)',
   'Horloge à aiguilles', 'Mesure – Temps'),

  ('Combien de temps?',
   'Est-ce qu''une récréation dure plus ou moins qu''une heure? Combien de minutes environ?',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Mesure',
   'Est-ce qu''une récréation dure plus ou moins qu''une heure? Combien de minutes environ?',
   'Comparer à des repères connus (émission TV, chanson)',
   'Horloge', 'Mesure – Temps'),

  ('15 minutes ou ¼ d''heure?',
   'Préfères-tu une récréation de 15 minutes ou de ¼ d''heure? Sont-elles pareilles?',
   math_id, 'Que choisirais-tu?', 15, '2e année', 'Causerie — Mesure',
   'Préfères-tu une récréation de 15 minutes ou de ¼ d''heure? Sont-elles pareilles?',
   'Reconnaître que 15 min = ¼ d''heure',
   'Horloge', 'Mesure – Temps'),

  ('Avant et après sur le calendrier',
   'Nous sommes le 15 mars. Dans combien de jours serons-nous en avril?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Mesure',
   'Nous sommes le 15 mars. Dans combien de jours serons-nous en avril?',
   'Compter les jours restants dans le mois',
   'Calendrier', 'Mesure – Temps'),

  ('Quelle surface est plus grande?',
   'Laquelle est la plus grande : la surface de ton livre ou celle de ton cahier? Comment vérifier?',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Mesure',
   'Laquelle est la plus grande : la surface de ton livre ou celle de ton cahier? Comment vérifier?',
   'Superposer, utiliser un quadrillage',
   'Livre, cahier, quadrillage', 'Mesure – Surface (aires)'),

  ('Pavage avec des carrés',
   'Combien de petits carrés faut-il pour couvrir ce rectangle? Estime d''abord.',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Mesure',
   'Combien de petits carrés faut-il pour couvrir ce rectangle? Estime d''abord.',
   'Remplir sans laisser d''espace ni superposer',
   'Petits carrés, rectangle', 'Mesure – Surface (aires)'),

  ('Surfaces différentes',
   'Feuille de papier, couverture de livre, tableau de la classe, timbre – Lequel est le plus grand?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Mesure',
   'Feuille de papier, couverture de livre, tableau de la classe, timbre – Lequel est le plus grand? Le plus petit?',
   'Classer du plus petit au plus grand',
   'Objets de la classe', 'Mesure – Surface'),

  ('Plus lourd ou plus léger?',
   'Qu''est-ce qui est plus lourd : ta gomme à effacer ou ton étui à crayons? Comment le sais-tu?',
   math_id, 'Estimation', 15, '1re année', 'Causerie — Mesure',
   'Qu''est-ce qui est plus lourd : ta gomme à effacer ou ton étui à crayons? Comment le sais-tu?',
   'Soupeser avec les mains, utiliser une balance',
   'Objets, balance', 'Mesure – Masse'),

  ('Quel contenant?',
   'Lequel contient le plus d''eau : ce verre ou cette bouteille? Comment vérifier?',
   math_id, 'Que choisirais-tu?', 15, '1re-2e année', 'Causerie — Mesure',
   'Lequel contient le plus d''eau : ce verre ou cette bouteille? Comment vérifier?',
   'Transvider pour comparer',
   'Verres, bouteilles, eau', 'Mesure – Capacité'),

  ('Mesurer quoi?',
   'Balance, règle, thermomètre, horloge – Lequel est différent? Que mesure chacun?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Mesure',
   'Balance, règle, thermomètre, horloge – Lequel est différent? Que mesure chacun?',
   'Associer instrument à grandeur mesurée',
   'Images d''instruments', 'Mesure – Instruments de mesure'),

  ('Chaud ou froid?',
   'Dehors il fait -10°C. Est-ce chaud ou froid? Que porterais-tu comme vêtements?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Mesure',
   'Dehors il fait -10°C. Est-ce chaud ou froid? Que porterais-tu comme vêtements?',
   'Associer température et sensation, vocabulaire',
   'Thermomètre, images', 'Mesure – Température'),

  ('Estimer la température',
   'Il neige dehors. La température est-elle plus proche de -15°C ou de 10°C?',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Mesure',
   'Il neige dehors. La température est-elle plus proche de -15°C ou de 10°C?',
   'Utiliser des repères (eau gèle à 0°C)',
   'Thermomètre', 'Mesure – Température'),

  ('Durées',
   '1 minute, 1 heure, 1 jour, 1 semaine – Lequel est différent? Pourquoi?',
   math_id, 'WODB', 15, '1re-2e année', 'Causerie — Mesure',
   '1 minute, 1 heure, 1 jour, 1 semaine – Lequel est différent? Pourquoi?',
   'Ordonner les unités, trouver des caractéristiques uniques',
   'Tableau blanc', 'Mesure – Temps'),

  -- ── 5. Statistique ─────────────────────────────────────────────────────────
  ('Le fruit préféré',
   'Quel est le fruit préféré de la classe? Comment pourrait-on le savoir?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Statistique',
   'Quel est le fruit préféré de la classe? Comment pourrait-on le savoir?',
   'Proposer un sondage, nommer des façons de collecter',
   'Tableau blanc', 'Statistique – Collecte de données'),

  ('Poser une bonne question',
   'Quelle question pourrait-on poser à la classe pour faire un sondage? La question est-elle claire?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Statistique',
   'Quelle question pourrait-on poser à la classe pour faire un sondage? La question est-elle claire?',
   'Formuler une question fermée, choix de réponses clairs',
   'Tableau blanc', 'Statistique – Collecte de données'),

  ('Sondage en action',
   'Préfères-tu la récréation intérieure ou extérieure? Comment allons-nous noter les réponses?',
   math_id, 'Que choisirais-tu?', 15, '1re année', 'Causerie — Statistique',
   'Préfères-tu la récréation intérieure ou extérieure? Comment allons-nous noter les réponses?',
   'Main levée, jetons, tableau de dénombrement',
   'Tableau de dénombrement', 'Statistique – Collecte de données'),

  ('Lire un tableau',
   'Voici un tableau : Pomme=8, Banane=5, Raisin=3. Quel fruit est le plus populaire? Le moins?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Statistique',
   'Voici un tableau : Pomme=8, Banane=5, Raisin=3. Quel fruit est le plus populaire? Le moins?',
   'Comparer les nombres, identifier le plus grand/petit',
   'Tableau affiché', 'Statistique – Tableaux de données'),

  ('Construire un tableau',
   'Nous avons fait un sondage sur les animaux préférés. Comment organiser nos résultats dans un tableau?',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Statistique',
   'Nous avons fait un sondage sur les animaux préférés. Comment organiser nos résultats dans un tableau?',
   'Créer des colonnes, titres, dénombrer',
   'Grande feuille, crayons', 'Statistique – Tableaux de données'),

  ('Représentations différentes',
   'Tableau, diagramme à bandes, pictogramme, liste – Lequel est différent? Pourquoi?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Statistique',
   'Tableau, diagramme à bandes, pictogramme, liste – Lequel est différent? Pourquoi?',
   'Comparer les caractéristiques de chaque représentation',
   'Exemples affichés', 'Statistique – Représentations graphiques'),

  ('Lire un pictogramme',
   'Dans ce pictogramme, chaque image de chat = 1 élève. Combien d''élèves préfèrent le chat?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Statistique',
   'Dans ce pictogramme, chaque image de chat = 1 élève. Combien d''élèves préfèrent le chat?',
   'Compter les images, associer à la quantité',
   'Pictogramme affiché', 'Statistique – Pictogrammes'),

  ('Pictogramme – estimer avant',
   'Avant de compter, estime combien d''élèves aiment le chien dans ce pictogramme.',
   math_id, 'Estimation', 15, '1re-2e année', 'Causerie — Statistique',
   'Avant de compter, estime combien d''élèves aiment le chien dans ce pictogramme.',
   'Observer la longueur de la rangée, estimer',
   'Pictogramme affiché', 'Statistique – Pictogrammes'),

  ('Créer un pictogramme',
   'Faisons un sondage dans la classe. Comment pourrait-on montrer les résultats avec des images?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Statistique',
   'Faisons un sondage dans la classe. Comment pourrait-on montrer les résultats avec des images?',
   'Choisir une image, une image = une donnée',
   'Autocollants, grande feuille', 'Statistique – Pictogrammes'),

  ('Lire un diagramme à bandes',
   'Dans ce diagramme à bandes, combien d''élèves préfèrent le hockey? Le soccer?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Statistique',
   'Dans ce diagramme à bandes, combien d''élèves préfèrent le hockey? Le soccer?',
   'Lire la hauteur de la bande, associer à l''axe',
   'Diagramme à bandes affiché', 'Statistique – Diagrammes à bandes'),

  ('Comparer des bandes',
   'Quelle bande est la plus haute? De combien est-elle plus haute que la plus courte?',
   math_id, 'Estimation', 15, '2e année', 'Causerie — Statistique',
   'Quelle bande est la plus haute? De combien est-elle plus haute que la plus courte?',
   'Lire les valeurs, calculer la différence',
   'Diagramme à bandes affiché', 'Statistique – Diagrammes à bandes'),

  ('Construire un diagramme à bandes',
   'Voici les données : Rouge=6, Bleu=9, Vert=4. Comment dessiner un diagramme à bandes?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Statistique',
   'Voici les données : Rouge=6, Bleu=9, Vert=4. Comment dessiner un diagramme à bandes?',
   'Tracer les axes, choisir l''échelle, colorier',
   'Papier quadrillé, crayons couleur', 'Statistique – Diagrammes à bandes'),

  ('Plus, moins, autant',
   'Dans ce diagramme, combien d''élèves préfèrent le chat? Le chien? Lequel est le plus populaire?',
   math_id, 'Number Talk', 15, '1re année', 'Causerie — Statistique',
   'Dans ce diagramme, combien d''élèves préfèrent le chat? Le chien? Lequel est le plus populaire?',
   'Comparer les quantités, utiliser plus/moins/autant',
   'Diagramme affiché', 'Statistique – Interprétation'),

  ('Combien en tout?',
   'Si 5 élèves aiment la pomme, 3 le raisin et 7 la banane, combien d''élèves ont répondu en tout?',
   math_id, 'Number Talk', 15, '1re-2e année', 'Causerie — Statistique',
   'Si 5 élèves aiment la pomme, 3 le raisin et 7 la banane, combien d''élèves ont répondu en tout?',
   'Additionner toutes les catégories',
   'Tableau de données', 'Statistique – Interprétation'),

  ('Analyser les données',
   'Pomme=10, Banane=2, Orange=10, Raisin=5 – Lequel est différent? Que remarques-tu?',
   math_id, 'WODB', 15, '2e année', 'Causerie — Statistique',
   'Pomme=10, Banane=2, Orange=10, Raisin=5 – Lequel est différent? Que remarques-tu?',
   'Trouver des valeurs égales, extrêmes, justifier',
   'Tableau de données', 'Statistique – Interprétation'),

  ('Prédire à partir des données',
   '8 élèves sur 20 préfèrent le soccer. Si on demandait à une autre classe, penses-tu que ce serait pareil?',
   math_id, 'Number Talk', 15, '2e année', 'Causerie — Statistique',
   '8 élèves sur 20 préfèrent le soccer. Si on demandait à une autre classe, penses-tu que ce serait pareil?',
   'Réfléchir à la variabilité, discuter',
   'Données de sondage', 'Statistique – Interprétation');

END $$;
